consulta de geometrias duplicadas

SELECT tbl1.ID_MUESTRA, tbl2.ID_MUESTRA
FROM PTOS_GeorrefParcel tbl1
LEFT JOIN PTOS_GeorrefParcel tbl2 
ON ST_Equals(tbl1.Shape, tbl2.Shape) = 1
WHERE tbl1.ID_MUESTRA <> tbl2.ID_MUESTRA
ORDER BY tbl1.ID_MUESTRA


SELECT tbl1.OBJECTID, tbl2.OBJECTID
FROM your_table tbl1
JOIN yout_table tbl2 ON tbl1.your_geometry_field.STEquals(tbl2.your_geometry_field) = 1
WHERE tbl1.OBJECTID <> tbl2.OBJECTID
ORDER BY tbl1.OBJECTID





SELECT ID_MUESTRA, Campaña
FROM PTOS_GeorrefParcel
WHERE ID_MUESTRA IN (
	SELECT DISTINCT(ID_MUESTRA)
	FROM PTOS_MISMAS_COOR
)
OR ID_MUESTRA IN
(
	SELECT DISTINCT(COL002)
	FROM PTOS_MISMAS_COOR
)


SELECT ID_MUESTRA, count(COL002) AS CUENTA
FROM PTOS_MISMAS_COOR
GROUP BY ID_MUESTRA
ORDER BY CUENTA DESC